#!/usr/bin/env bash
#A small metronome written for the command line

function Play {
	tempo=$(bc -l <<< 60/"$1")
	echo "Your metronomer is set and ready at "$1" BPM. Press Ctrl+C to quit"
	while [[ : ]]; do
		FirstSound 
		SecondSound
		SecondSound
		SecondSound
	done
}

function FirstSound {
	aplay -q "${BASH_SOURCE%/*}"/src/first.wav & echo -ne ' + ' & sleep "$tempo"
}

function SecondSound {
	aplay -q "${BASH_SOURCE%/*}"/src/second.wav & echo -ne ' - ' &sleep "$tempo"
}

Play $1
