#!/usr/bin/env bash
#A small metronome written for the command line

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function Play {
	# main function
	tempo=$(bc -l <<< 60/"$1")
	echo "Your metonomer is set and ready at "$1" BPM. Press Ctrl+C to quit"
	while [[ : ]]; do
		FirstSound 
		SecondSound
		SecondSound
		SecondSound
	done
}

function FirstSound {
	aplay -q "$DIR"/src/first.wav & echo -ne ' + ' & sleep "$tempo"
}

function SecondSound {
	aplay -q "$DIR"/src/second.wav & echo -ne ' - ' &sleep "$tempo"
}

Play $1
